Development
AlejoCode/apple-web-design-just-html-css pull request #1
Opened 2019-03-12 20:55 UTC by AlejoCode

Hi.

Thank you so much for your help

@zenott and I ended the project and wanted to know feedback about you guys

Cheers

2019-03-12 23:31 UTC, zlayabekrija requested changes
Great work guys, some small things to change, please follow them up.
Please make read me file, it's very important for the project.
Please follow the notes in the code.
Please fix the required notes, and re submit review request.
Happy coding

2019-03-12 23:31 UTC, zlayabekrija commented on assets/css/style.css
> +  width: 1440px;
I guess that you wanted to have max-width. With this width it looks way to big for my screen, please fix it. My screen size is 1280px.

2019-03-12 23:31 UTC, zlayabekrija commented on index.html
> +                    <a href="/web/20140301004610/http://www.apple.com/pr/" ></a>Media Info</a></li><li>
one extra `</a>` tag

2019-03-12 23:31 UTC, zlayabekrija commented on index.html
> +      <section class="hero">
By convention `<section>` tag requires heading tag (h1,h2...). Please use header,main,aside tags ...
I would call this header. Convetion isn't must it's only good practise.

2019-03-12 23:31 UTC, zlayabekrija commented on index.html
> +      <section class="footer">
please use footer instead of section

2019-03-14 21:47 UTC, AlejoCode commented
Hi we made the changes and need approval please

2019-03-14 23:49 UTC, zlayabekrija approved these changes
Great work, thumbs up 👍  from me.
Happy coding :)

2019-03-15 21:34 UTC, merged